import antfu from '@antfu/eslint-config'

export default antfu(
  {
    vue: true,
    typescript: true,
    prettier: true,
  },
  {
    ignores: [
      'node_modules/**',
      '.husky/**',
      '.vscode/**',
      'dist/**',
      '.parcel-cache/**',
    ],
    rules: {
      // Regras herdadas do Biome
      'no-console': 'warn',
      'no-debugger': 'warn',
      'no-unused-vars': 'off',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-constant-condition': 'error',
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-self-assign': 'error',
      'no-redeclare': 'error',
      'no-shadow': ['error', { builtinGlobals: false }],
      'no-with': 'error',
      'no-useless-catch': 'error',
      'no-setter-return': 'error',
      'no-unused-labels': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-func-assign': 'error',
      'no-class-assign': 'error',
      'no-import-assign': 'error',
      'no-global-assign': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-extra-boolean-cast': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-control-regex': 'error',
      'no-misleading-character-class': 'error',
      'no-prototype-builtins': 'error',
      'prefer-exponentiation-operator': 'off',
      'getter-return': 'error',

      // Vue
      'vue/no-deprecated-slot-attribute': 'off',
      'vue/no-template-target-blank': 'error',
      'vue/no-v-html': 'off',
      'vue/require-valid-default-prop': 'off',
      'vue/no-unused-components': 'warn',
    },
  },
)
