export interface Institutions {
    id: string;
    name?: string;
}
export interface SchoolFormValues {
    id: string | undefined;
    idpes: number | null;
    INEPCode: string;
    name: string;
    corporateName: string;
    cnpj: string | null;
    educationNetwork: string | null;
    phone: string;
    phone2: string;
    acronym: string;
    blockJournalEntries: string | null;
    operationalStatus: string | null;
    usesAlternativeRules: string | null;
    administrativeDependency: string | null;
    address: string;
    addressNumber: string;
    additionalInfo: string;
    neighborhood: string;
    city: string;
    state: string;
    postalCode: string;
    unusualLocation: string | null;
    email: string;
    website: string;
    operatingLocation: string | null;
    buildingUsage: string | null;
    sharedSchool: string | null;
    sharedSchoolINEPCode: string;
    potableWaterAvailable: string | null;
    sewageAvailable: string | null;
    electricityAvailable: string | null;
    wasteDisposal: string | null;
    wasteTreatmentBySchool: string | null;
    foodServiceAvailable: string | null;
    communitySharedSpaces: string | null;
    usesSurroundingSpaces: string | null;
    specificFacilities: string | null;
    generalUseRooms: string[] | null;
    labsAndFunctionalAreas: string[] | null;
    supportFacilities: string[] | null;
    insideClassrooms: number | null;
    outsideClassrooms: number | null;
    refrigeratedClassrooms: number | null;
    accessibleClassrooms: number | null;
    internetAvailable: string | null;
    localNetworkAvailable: string | null;
    devicesUsedByStudents: string[] | null;
    connectionType: string[] | null;
    availableDesktops: number | null;
    availableLaptops: number | null;
    availableTablets: number | null;
    teachingEquipments: string[] | null;
    administrativeStaffNumber: number | null;
    teachingStaffNumber: number | null;
    generalServicesStaffNumber: number | null;
    securityStaffNumber: number | null;
    schoolManagementStaffNumber: number | null;
    healthcareStaffNumber: number | null;
    socialAssistanceStaffNumber: number | null;
    specializedAssistance: string | null;
    elementaryEducationModel: string | null;
    wasPedagogicalProjectUpdated: string | null;
    indigenousEducationAvailable: string | null;
    linkedWithSuperiorEducation: string | null;
    collegiateBodies: string[] | null;
    studentSelectionCriteria: string[] | null;
    indigenousEducationLanguages: string[] | null;
    pedagogicalMaterials: string[] | null;
    headSchoolCode?: number;
    IESCode?: number;
    institutionId?: string | null;
    active?: boolean | null;
    abbreviation?: string;
    longitude?: string;
    latitude?: string;
    totalArea?: string;
    builtArea?: string;
    availableArea?: string;
    blockDiaryEntries?: boolean | null;
    regulation?: number | null;
    logoUrl?: string;
    access?: number | null;
    managerid?: string;
    managerPosition?: string;
    operationLocation?: string;
    condition?: number | null;
    sharedSchooLinePCode?: number | null;
    creationDecree?: string;
    numberOfFloors?: number | null;
    floorType?: number | null;
    energyMeter?: number | null;
    hasExternalArea?: boolean | null;
    metadata?: any | null;
    createdAt?: string;
    deletedAt?: string | null;
    updatedAt?: string | null;
    updatedBy?: string;
    tenantId?: string;
    userCreated?: string;
}