-- Criação de tabela para relacionamento entre escola e curso
CREATE TABLE
    IF NOT EXISTS public.school_course (
        id uuid NOT NULL DEFAULT gen_random_uuid (),
        created_at timestamp
        with
            time zone NOT NULL DEFAULT now (),
            school_id uuid NULL,
            course_id uuid NULL,
            CONSTRAINT school_course_pkey PRIMARY KEY (id),
            CONSTRAINT school_course_course_id_fkey FOREIGN KEY (course_id) REFERENCES course (id),
            CONSTRAINT school_course_school_id_fkey FOREIGN KEY (school_id) REFERENCES school (id)
    ) TABLESPACE pg_default;

-- Criação de tabela para configurações na escola
create table
    IF NOT EXISTS public.school_settings (
        id uuid not null default gen_random_uuid (),
        created_at timestamp
        with
            time zone not null default now (),
            date_opening date null,
            date_closing date null,
            school_days numeric null,
            date_start date null,
            date_end date null,
            institution_id uuid null,
            constraint school_settings_pkey primary key (id),
            constraint school_settings_institution_id_fkey foreign key (institution_id) references institution (id)
    ) tablespace pg_default;

-- Criação de tabela para configurações da instituição
create table
    IF NOT EXISTS public.institution_settings (
        id bigint generated by default as identity not null,
        created_at timestamp
        with
            time zone not null default now (),
            institution_id uuid null,
            date_opening date null,
            date_closing date null,
            school_days numeric null,
            date_start date null,
            date_end date null,
            constraint institution_settings_pkey primary key (id),
            constraint institution_settings_institution_id_fkey foreign key (institution_id) references institution (id)
    ) tablespace pg_default;